FROM runescrape-base

ARG REACT_ENV

# Make NGINX run on the foreground
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
# Remove default configuration from Nginx
RUN rm /etc/nginx/conf.d/default.conf
# Copy the modified Nginx conf
COPY config/nginx.conf /etc/nginx/conf.d/
# Copy the base uWSGI ini file to enable default dynamic uwsgi process number
COPY config/uwsgi.ini /etc/uwsgi/

COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY requirements.txt /tmp/

RUN pip install -U pip
RUN pip install -r /tmp/requirements.txt
WORKDIR /frontend

RUN python build.py $REACT_ENV;

WORKDIR /backend
COPY ./backend /backend

CMD ["/usr/bin/supervisord"]
