version: '2.2'

services:
  web:
    build: .
    image: runescrape:latest
    command: /usr/bin/supervisord
    restart: always
    networks:
      - db
      - esnet
    volumes:
      - /home/ubuntu/idb:/idb
    ports:
      - "80:80"
    depends_on:
      - dbpostgres
      - elasticsearch
    env_file:
      - .env
  dbpostgres:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5342:5342"
    networks:
      - db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: runescrape
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

volumes:
  pgdata:
  esdata1:
    driver: local

networks:
  db:
    driver: bridge
  esnet:
    driver: bridge
